/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import GradedRings.WeightedEvaluation
public import GradedRings.WeightedBlockAdjoin
public import GradedRings.Veronese
public import Mathlib.RingTheory.GradedAlgebra.FiniteType

@[expose] public section

/-!
# Finite generation of a positive Veronese in degree one

A finite positive-weight homogeneous generating family gives finitely many generators in
degree one of the selected-component ring, over its actual degree-zero component.
-/

set_option warningAsError true

noncomputable section

namespace GradedRing.Veronese

variable {S σ ι : Type*} [CommRing S] [SetLike σ S] [AddSubgroupClass σ S]
  (𝒮 : ℕ → σ) [GradedRing 𝒮] [Fintype ι]

/-- A finite family of positive-weight homogeneous generators yields a finite family
in the new degree-one component that generates the *whole* selected ring over its
actual degree-zero ring. -/
theorem exists_finite_degree_one_generators
    (w : ι → ℕ) (hw : ∀ i, 0 < w i) (x : ∀ i, 𝒮 (w i))
    (hgen : Algebra.adjoin (𝒮 0) (Set.range (fun i => (x i : S))) = ⊤) :
    ∃ T : Set (VeroneseRing 𝒮 (Finsupp.weightedBlockSize w)), T.Finite ∧
      T ⊆ (component 𝒮 (Finsupp.weightedBlockSize w) 1 : Set _) ∧
      Algebra.adjoin (component 𝒮 (Finsupp.weightedBlockSize w) 0) T = ⊤ := by
  classical
  let D := Finsupp.weightedBlockSize w
  have hD : 0 < D := Finsupp.weightedBlockSize_pos w hw
  let e : MvPolynomial ι (𝒮 0) →ₐ[𝒮 0] S := MvPolynomial.aeval (fun i => (x i : S))
  let Index := {d : ι →₀ ℕ // Finsupp.weight w d = D}
  have : Finite Index :=
    (Finsupp.finite_of_nat_weight_eq w (fun i => Nat.ne_of_gt (hw i)) D).to_subtype
  have hmonomial (d : Index) : e (MvPolynomial.monomial d.1 (1 : 𝒮 0)) ∈ 𝒮 (D * 1) := by
    simpa only [mul_one, d.property] using
      (MvPolynomial.isWeightedHomogeneous_monomial w d.1 (1 : 𝒮 0) rfl).aeval_mem
        𝒮 w x
  let lift (d : Index) : VeroneseRing 𝒮 D :=
    (exists_component 𝒮 D 1 ⟨e (MvPolynomial.monomial d.1 (1 : 𝒮 0)),
      hmonomial d⟩).choose
  have hlift (d : Index) : lift d ∈ component 𝒮 D 1 ∧
      inclusion 𝒮 D (lift d) = e (MvPolynomial.monomial d.1 (1 : 𝒮 0)) :=
    (exists_component 𝒮 D 1 ⟨e (MvPolynomial.monomial d.1 (1 : 𝒮 0)),
      hmonomial d⟩).choose_spec
  let T : Set (VeroneseRing 𝒮 D) := Set.range lift
  have hTfinite : T.Finite := Set.finite_range lift
  have hTdegree : T ⊆ (component 𝒮 D 1 : Set (VeroneseRing 𝒮 D)) := by
    rintro t ⟨d, rfl⟩
    exact (hlift d).1
  let U : Subalgebra (component 𝒮 D 0) (VeroneseRing 𝒮 D) := Algebra.adjoin _ T
  let P : Set (MvPolynomial ι (𝒮 0)) :=
    (fun d : ι →₀ ℕ => MvPolynomial.monomial d (1 : 𝒮 0)) ''
      {d | Finsupp.weight w d = D}
  have hpoly {p : MvPolynomial ι (𝒮 0)} (hp : p ∈ Algebra.adjoin (𝒮 0) P) :
      ∃ t : VeroneseRing 𝒮 D, t ∈ U ∧ inclusion 𝒮 D t = e p := by
    induction hp using Algebra.adjoin_induction with
    | mem p hp =>
        obtain ⟨d, hd, rfl⟩ := hp
        refine ⟨lift ⟨d, hd⟩, Algebra.subset_adjoin (Set.mem_range_self _), ?_⟩
        exact (hlift ⟨d, hd⟩).2
    | algebraMap r =>
        let t : VeroneseRing 𝒮 D :=
          algebraMap (component 𝒮 D 0) (VeroneseRing 𝒮 D)
            ((zeroRingEquiv 𝒮 D hD).symm r)
        refine ⟨t, U.algebraMap_mem _, ?_⟩
        change inclusion 𝒮 D (((zeroRingEquiv 𝒮 D hD).symm r : component 𝒮 D 0) :
          VeroneseRing 𝒮 D) = e (algebraMap _ _ r)
        rw [← zeroRingEquiv_apply 𝒮 D hD]
        simp only [RingEquiv.apply_symm_apply, e, AlgHom.commutes,
          SetLike.GradeZero.algebraMap_apply]
    | add p q _ _ ihp ihq =>
        obtain ⟨t, ht, heq⟩ := ihp
        obtain ⟨s, hs, hsq⟩ := ihq
        refine ⟨t + s, U.add_mem ht hs, ?_⟩
        rw [map_add, heq, map_add, hsq]
    | mul p q _ _ ihp ihq =>
        obtain ⟨t, ht, heq⟩ := ihp
        obtain ⟨s, hs, hsq⟩ := ihq
        refine ⟨t * s, U.mul_mem ht hs, ?_⟩
        rw [map_mul, heq, map_mul, hsq]
  refine ⟨T, hTfinite, hTdegree, ?_⟩
  apply top_unique
  intro t _
  have hall : ∀ t : VeroneseRing 𝒮 D, t ∈ U := by
    intro t
    induction t using DirectSum.induction_on with
    | zero => exact U.zero_mem
    | of j a =>
        obtain ⟨p, hp, heq⟩ := MvPolynomial.exists_isWeightedHomogeneous_aeval
          𝒮 w x hgen a.property
        have hp' : p ∈ Algebra.adjoin (𝒮 0) P := by
          apply MvPolynomial.IsWeightedHomogeneous.mem_adjoin_weightedBlockSize w hw j
          simpa only [D, Nat.mul_comm] using hp
        obtain ⟨s, hs, hseval⟩ := hpoly hp'
        have hsame : s = DirectSum.of (fun k : ℕ => 𝒮 (D * k)) j a :=
          inclusion_injective 𝒮 D hD
            (hseval.trans (heq.trans (inclusion_of 𝒮 D j a).symm))
        exact hsame ▸ hs
    | add a b ha hb => exact U.add_mem ha hb
  exact hall t

/-- A finite-type naturally graded algebra has a positive Veronese generated by
finitely many elements in its new degree one, over its actual degree zero. -/
theorem exists_positive_finite_degree_one_generators
    [Algebra.FiniteType (𝒮 0) S] :
    ∃ n : ℕ, 0 < n ∧ ∃ T : Set (VeroneseRing 𝒮 n), T.Finite ∧
      T ⊆ (component 𝒮 n 1 : Set _) ∧ Algebra.adjoin (component 𝒮 n 0) T = ⊤ := by
  classical
  obtain ⟨F, hF, hdegree⟩ :=
    GradedAlgebra.exists_finset_adjoin_eq_top_and_homogeneous_ne_zero 𝒮
  let w (i : F) : ℕ := (hdegree i.1 i.2).choose
  have hw (i : F) : 0 < w i := Nat.pos_of_ne_zero (hdegree i.1 i.2).choose_spec.1
  let x (i : F) : 𝒮 (w i) := ⟨i.1, (hdegree i.1 i.2).choose_spec.2⟩
  have hgen : Algebra.adjoin (𝒮 0) (Set.range (fun i : F => (x i : S))) = ⊤ := by
    have heq : Set.range (fun i : F => (x i : S)) = (F : Set S) := by
      apply Set.ext
      intro s
      constructor
      · rintro ⟨i, rfl⟩
        exact i.2
      · intro hs
        exact ⟨⟨s, hs⟩, rfl⟩
    rw [heq]
    exact hF
  obtain ⟨T, hTfinite, hTdegree, hTgen⟩ :=
    exists_finite_degree_one_generators 𝒮 w hw x hgen
  exact ⟨Finsupp.weightedBlockSize w, Finsupp.weightedBlockSize_pos w hw,
    T, hTfinite, hTdegree, hTgen⟩

end GradedRing.Veronese
