/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import Mathlib.RingTheory.GradedAlgebra.RingHom
public import Mathlib.RingTheory.MvPolynomial.Homogeneous

/-!
# Homogeneous lifts in degree-one-generated graded rings

A surjective graded ring map is surjective on each whole homogeneous component.
Polynomial evaluation in all degree-one elements is graded, giving homogeneous
polynomial lifts when those elements generate the ring over its actual degree-zero ring.
-/

@[expose] public section

set_option warningAsError true

namespace GradedRingHom

variable {ι A B σ τ : Type*} [DecidableEq ι] [AddMonoid ι]
  [Semiring A] [Semiring B] [SetLike σ A] [AddSubmonoidClass σ A]
  [SetLike τ B] [AddSubmonoidClass τ B]
  (𝒜 : ι → σ) (ℬ : ι → τ) [GradedRing 𝒜] [GradedRing ℬ]

/-- An ambient-surjective graded ring map is surjective on every homogeneous component. -/
theorem surjective_gradedAddHom (f : 𝒜 →+*ᵍ ℬ) (hf : Function.Surjective f)
    (i : ι) : Function.Surjective (f.gradedAddHom i) := by
  classical
  intro b
  obtain ⟨a, ha⟩ := hf (b : B)
  refine ⟨DirectSum.decompose 𝒜 a i, Subtype.ext ?_⟩
  change f (DirectSum.decompose 𝒜 a i : A) = (b : B)
  rw [f.map_directSumDecompose, ha]
  exact DirectSum.decompose_of_mem_same ℬ b.property

end GradedRingHom

namespace MvPolynomial

variable {S σ : Type*} [CommRing S] [SetLike σ S] [AddSubgroupClass σ S]
  (𝒮 : ℕ → σ) [GradedRing 𝒮]

private theorem evalDegreeOne_pow_mem (a : 𝒮 1) (k : ℕ) : (a : S) ^ k ∈ 𝒮 k := by
  induction k with
  | zero => simpa using SetLike.one_mem_graded 𝒮
  | succ k ih =>
    simpa [pow_succ, Nat.add_comm] using
      (SetLike.GradedMul.mul_mem ih a.property : (a : S) ^ k * a ∈ 𝒮 (k + 1))

private theorem evalDegreeOne_monomial_mem (d : (𝒮 1) →₀ ℕ) (r : 𝒮 0) :
    aeval (fun a : 𝒮 1 => (a : S)) (monomial d r) ∈ 𝒮 d.degree := by
  classical
  have hprod : ∀ t : Finset (𝒮 1),
      (∏ a ∈ t, (a : S) ^ d a) ∈ 𝒮 (∑ a ∈ t, d a) := by
    intro t
    induction t using Finset.induction_on with
    | empty => simpa using SetLike.one_mem_graded 𝒮
    | @insert a t hat ih =>
      simpa [Finset.prod_insert hat, Finset.sum_insert hat] using
        (SetLike.GradedMul.mul_mem (evalDegreeOne_pow_mem 𝒮 a (d a)) ih)
  rw [aeval_monomial, Finsupp.prod, Finsupp.degree_apply,
    SetLike.GradeZero.algebraMap_apply]
  simpa only [zero_add] using
    (SetLike.GradedMul.mul_mem (show (r : S) ∈ 𝒮 0 from r.property)
      (hprod d.support) : (r : S) * (∏ a ∈ d.support, (a : S) ^ d a) ∈
        𝒮 (0 + ∑ a ∈ d.support, d a))

/-- Evaluating a homogeneous polynomial in degree-one elements preserves its degree. -/
theorem isHomogeneous_aeval_degreeOne {m : ℕ} {p : MvPolynomial (𝒮 1) (𝒮 0)}
    (hp : p.IsHomogeneous m) :
    aeval (fun a : 𝒮 1 => (a : S)) p ∈ 𝒮 m := by
  classical
  rw [← p.support_sum_monomial_coeff, map_sum]
  apply sum_mem
  intro d hd
  have hdegree : d.degree = m := by
    rw [Finsupp.degree_eq_weight_one]
    exact hp (mem_support_iff.mp hd)
  simpa only [hdegree] using evalDegreeOne_monomial_mem 𝒮 d (p.coeff d)

/-- Evaluation by all degree-one elements as a degree-preserving graded map. -/
noncomputable def aevalDegreeOneGradedHom :
    (homogeneousSubmodule (𝒮 1) (𝒮 0)) →+*ᵍ 𝒮 := by
  letI : GradedAlgebra (homogeneousSubmodule (𝒮 1) (𝒮 0)) := gradedAlgebra
  exact { (aeval (fun a : 𝒮 1 => (a : S))).toRingHom with
    map_mem := fun hp => isHomogeneous_aeval_degreeOne 𝒮 hp }

/-- Every homogeneous element has a homogeneous polynomial lift when the graded ring is
generated by its entire degree-one component over its actual degree-zero ring. -/
theorem exists_isHomogeneous_aeval (hgen : Algebra.adjoin (𝒮 0) (𝒮 1 : Set S) = ⊤)
    {m : ℕ} {s : S} (hs : s ∈ 𝒮 m) :
    ∃ p : MvPolynomial (𝒮 1) (𝒮 0), p.IsHomogeneous m ∧
      aeval (fun a : 𝒮 1 => (a : S)) p = s := by
  let _ : GradedAlgebra (homogeneousSubmodule (𝒮 1) (𝒮 0)) := gradedAlgebra
  have hsurj : Function.Surjective (aeval (fun a : 𝒮 1 => (a : S)) :
      MvPolynomial (𝒮 1) (𝒮 0) →ₐ[𝒮 0] S) := by
    rw [← AlgHom.range_eq_top, aeval_range]
    simpa [Subtype.range_coe] using hgen
  obtain ⟨p, hp⟩ := GradedRingHom.surjective_gradedAddHom
    (homogeneousSubmodule (𝒮 1) (𝒮 0)) 𝒮
    (aevalDegreeOneGradedHom 𝒮) hsurj m ⟨s, hs⟩
  exact ⟨p, p.property, congrArg Subtype.val hp⟩

end MvPolynomial
