/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import GradedRings.SymmetricAlgebra
public import CoherentModules.Algebra.TrivSqZeroExt.Finite
public import Mathlib.Algebra.TrivSqZeroExt.Ideal
public import Mathlib.Algebra.Module.RingHom
public import Mathlib.RingTheory.Ideal.Cotangent
public import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# The first-order quotient of a symmetric algebra

The augmentation ideal is the kernel of evaluation at zero. Its square defines the
first-order quotient, whose degree-one part is the original module without any
finiteness or freeness assumption. The cotangent module carries the scalar action
restricted from the symmetric algebra along its algebra map.

Use `open scoped TrivSqZeroExt` for the canonical opposite action and central scalar
structure on arbitrary modules over a commutative ring. This scope also makes the
quotient algebra equivalence compatible with `TrivSqZeroExt.map` and ideal transport.
The conormal comparison restricts Mathlib's `Ideal.cotangentEquivIdeal` and
uses the projection-kernel equivalence from the released coherent-modules library.
-/

@[expose] public section

open scoped TrivSqZeroExt

namespace SymmetricAlgebra

universe uR uM uN

variable {R : Type uR} {M : Type uM}
variable [CommRing R] [AddCommGroup M] [Module R M]

/-- The kernel of evaluation of the symmetric algebra at zero. -/
def augmentationIdeal : Ideal (SymmetricAlgebra R M) :=
  RingHom.ker (algebraMapInv (R := R) (M := M)).toRingHom

/-- Evaluation at zero detects membership in the augmentation ideal. -/
@[simp] theorem mem_augmentationIdeal_iff (x : SymmetricAlgebra R M) :
    x ∈ augmentationIdeal (R := R) (M := M) ↔
      algebraMapInv (R := R) (M := M) x = 0 :=
  RingHom.mem_ker

/-- The augmentation ideal is generated by the degree-one elements. -/
theorem augmentationIdeal_eq_span_ι :
    augmentationIdeal (R := R) (M := M) =
      Ideal.span (Set.range (ι R M)) := by
  apply le_antisymm
  · intro x hx
    have scalarPart (y : SymmetricAlgebra R M) :
        y - algebraMap R (SymmetricAlgebra R M)
          (algebraMapInv (R := R) (M := M) y) ∈
          Ideal.span (Set.range (ι R M)) := by
      induction y using SymmetricAlgebra.induction with
      | algebraMap r => simp [algebraMapInv]
      | ι m => simpa [algebraMapInv_ι] using
          (Ideal.subset_span (Set.mem_range_self m) :
            ι R M m ∈ Ideal.span (Set.range (ι R M)))
      | mul a b ha hb =>
          convert Ideal.add_mem _
            ((Ideal.span (Set.range (ι R M))).mul_mem_right b ha)
            ((Ideal.span (Set.range (ι R M))).mul_mem_left
              (algebraMap R (SymmetricAlgebra R M)
                (algebraMapInv (R := R) (M := M) a)) hb) using 1
          simp only [map_mul, sub_mul, mul_sub]
          ring
      | add a b ha hb =>
          convert Ideal.add_mem _ ha hb using 1
          simp only [map_add, sub_add, add_sub]
          abel
    simpa [(mem_augmentationIdeal_iff (R := R) (M := M) x).mp hx] using scalarPart x
  · rw [Ideal.span_le]
    rintro _ ⟨m, rfl⟩
    exact (mem_augmentationIdeal_iff (R := R) (M := M) _).mpr (algebraMapInv_ι m)

/-- Each degree-one element lies in the augmentation ideal. -/
theorem ι_mem_augmentationIdeal (m : M) :
    ι R M m ∈ augmentationIdeal (R := R) (M := M) := by
  exact (mem_augmentationIdeal_iff (R := R) (M := M) _).2 (algebraMapInv_ι m)

/-- The first-order symmetric-algebra quotient as a trivial square-zero extension,
for arbitrary modules over an arbitrary commutative ring. -/
noncomputable def squareZeroQuotientEquiv :
    (SymmetricAlgebra R M ⧸ (augmentationIdeal (R := R) (M := M)) ^ 2) ≃ₐ[R]
      TrivSqZeroExt R M := by
  let forward : SymmetricAlgebra R M →ₐ[R] TrivSqZeroExt R M :=
    lift (TrivSqZeroExt.inrHom R M)
  have projection : (TrivSqZeroExt.fstHom R R M).comp forward =
      algebraMapInv (R := R) (M := M) := by
    apply SymmetricAlgebra.algHom_ext
    ext m
    simp [forward, algebraMapInv]
  have mapsToKernel (x : SymmetricAlgebra R M)
      (hx : x ∈ augmentationIdeal (R := R) (M := M)) :
      forward x ∈ TrivSqZeroExt.kerIdeal R M := by
    change (TrivSqZeroExt.fstHom R R M) (forward x) = 0
    rw [← AlgHom.comp_apply, projection]
    exact (mem_augmentationIdeal_iff (R := R) (M := M) x).mp hx
  have descends (x : SymmetricAlgebra R M)
      (hx : x ∈ (augmentationIdeal (R := R) (M := M)) ^ 2) : forward x = 0 := by
    have mapped : forward x ∈
        Ideal.map forward.toRingHom ((augmentationIdeal (R := R) (M := M)) ^ 2) :=
      Ideal.mem_map_of_mem forward.toRingHom hx
    rw [Ideal.map_pow] at mapped
    have inclusion : Ideal.map forward.toRingHom
        (augmentationIdeal (R := R) (M := M)) ≤ TrivSqZeroExt.kerIdeal R M :=
      Ideal.map_le_iff_le_comap.mpr mapsToKernel
    have inSquare : forward x ∈ (TrivSqZeroExt.kerIdeal R M) ^ 2 :=
      pow_le_pow_left' inclusion 2 mapped
    simpa only [TrivSqZeroExt.kerIdeal_sq, Ideal.mem_bot] using inSquare
  let descent : (SymmetricAlgebra R M ⧸
      (augmentationIdeal (R := R) (M := M)) ^ 2) →ₐ[R] TrivSqZeroExt R M :=
    Ideal.Quotient.liftₐ _ forward descends
  let quotient : SymmetricAlgebra R M →ₐ[R]
      (SymmetricAlgebra R M ⧸ (augmentationIdeal (R := R) (M := M)) ^ 2) :=
    Ideal.Quotient.mkₐ R _
  let generator : M →ₗ[R]
      (SymmetricAlgebra R M ⧸ (augmentationIdeal (R := R) (M := M)) ^ 2) :=
    quotient.toLinearMap.comp (ι R M)
  have generator_mul (m n : M) : generator m * generator n = 0 := by
    change Ideal.Quotient.mk _ (ι R M m) * Ideal.Quotient.mk _ (ι R M n) = 0
    rw [← map_mul]
    apply Ideal.Quotient.eq_zero_iff_mem.mpr
    rw [pow_two]
    exact Ideal.mul_mem_mul (ι_mem_augmentationIdeal m) (ι_mem_augmentationIdeal n)
  let reverse : TrivSqZeroExt R M →ₐ[R]
      (SymmetricAlgebra R M ⧸ (augmentationIdeal (R := R) (M := M)) ^ 2) :=
    TrivSqZeroExt.liftEquivOfComm ⟨generator, generator_mul⟩
  have descent_ι (m : M) : descent (Ideal.Quotient.mk _ (ι R M m)) =
      TrivSqZeroExt.inr m := by
    change forward (ι R M m) = TrivSqZeroExt.inr m
    simp [forward]
  have reverse_inr (m : M) : reverse (TrivSqZeroExt.inr m) =
      Ideal.Quotient.mk _ (ι R M m) := by
    simp [reverse, generator, quotient]
  have rightInverse : descent.comp reverse = AlgHom.id R (TrivSqZeroExt R M) := by
    apply TrivSqZeroExt.algHom_ext
    intro m
    simp only [AlgHom.comp_apply, AlgHom.id_apply, reverse_inr, descent_ι]
  have leftInverse : reverse.comp descent =
      AlgHom.id R (SymmetricAlgebra R M ⧸
        (augmentationIdeal (R := R) (M := M)) ^ 2) := by
    apply Ideal.Quotient.algHom_ext
    apply SymmetricAlgebra.algHom_ext
    apply LinearMap.ext
    intro m
    change reverse (descent (Ideal.Quotient.mk _ (ι R M m))) =
      Ideal.Quotient.mk _ (ι R M m)
    rw [descent_ι, reverse_inr]
  exact AlgEquiv.ofAlgHom descent reverse rightInverse leftInverse

/-- The quotient equivalence sends a degree-one generator to its square-zero coordinate. -/
@[simp] theorem squareZeroQuotientEquiv_mk_ι (m : M) :
    squareZeroQuotientEquiv (R := R) (M := M)
      (Ideal.Quotient.mk _ (ι R M m)) = TrivSqZeroExt.inr m := by
  change lift (TrivSqZeroExt.inrHom R M) (ι R M m) = TrivSqZeroExt.inr m
  simp

/-- The quotient equivalence preserves the scalar summand. -/
@[simp] theorem squareZeroQuotientEquiv_mk_algebraMap (r : R) :
    squareZeroQuotientEquiv (R := R) (M := M)
      (Ideal.Quotient.mk _ (algebraMap R (SymmetricAlgebra R M) r)) =
        TrivSqZeroExt.inl r := by
  change lift (TrivSqZeroExt.inrHom R M)
    (algebraMap R (SymmetricAlgebra R M) r) = TrivSqZeroExt.inl r
  simp [TrivSqZeroExt.algebraMap_eq_inl]

/-- The inverse quotient equivalence sends scalar elements to scalar classes. -/
@[simp] theorem squareZeroQuotientEquiv_symm_inl (r : R) :
    (squareZeroQuotientEquiv (R := R) (M := M)).symm (TrivSqZeroExt.inl r) =
      Ideal.Quotient.mk _ (algebraMap R (SymmetricAlgebra R M) r) := by
  apply (squareZeroQuotientEquiv (R := R) (M := M)).injective
  simp [TrivSqZeroExt.algebraMap_eq_inl]

/-- The inverse quotient equivalence sends square-zero elements to degree-one classes. -/
@[simp] theorem squareZeroQuotientEquiv_symm_inr (m : M) :
    (squareZeroQuotientEquiv (R := R) (M := M)).symm (TrivSqZeroExt.inr m) =
      Ideal.Quotient.mk _ (ι R M m) := by
  apply (squareZeroQuotientEquiv (R := R) (M := M)).injective
  simp

/-- Projection after the quotient equivalence is evaluation at zero. -/
@[simp] theorem squareZeroQuotientEquiv_fst (x : SymmetricAlgebra R M) :
    TrivSqZeroExt.fstHom R R M
      (squareZeroQuotientEquiv (R := R) (M := M) (Ideal.Quotient.mk _ x)) =
        algebraMapInv (R := R) (M := M) x := by
  have compatible :
      ((TrivSqZeroExt.fstHom R R M).comp
        (squareZeroQuotientEquiv (R := R) (M := M)).toAlgHom).comp
          (Ideal.Quotient.mkₐ R _) = algebraMapInv (R := R) (M := M) := by
    apply SymmetricAlgebra.algHom_ext
    ext m
    simp [algebraMapInv_ι]
  exact congrArg (fun f : SymmetricAlgebra R M →ₐ[R] R => f x) compatible

/-- The image of the quotient's cotangent ideal is the square-zero extension's
projection kernel; neither of these ideals is the original augmentation ideal. -/
theorem squareZeroQuotientEquiv_cotangentIdeal :
    Ideal.map (squareZeroQuotientEquiv (R := R) (M := M)).toRingHom
      (augmentationIdeal (R := R) (M := M)).cotangentIdeal =
        TrivSqZeroExt.kerIdeal R M := by
  apply le_antisymm
  · apply Ideal.map_le_iff_le_comap.mpr
    rintro _ ⟨x, hx, rfl⟩
    change TrivSqZeroExt.fstHom R R M
      (squareZeroQuotientEquiv (R := R) (M := M) (Ideal.Quotient.mk _ x)) = 0
    rw [squareZeroQuotientEquiv_fst]
    exact (mem_augmentationIdeal_iff (R := R) (M := M) x).mp hx
  · intro x hx
    have x_inr := (TrivSqZeroExt.mem_kerIdeal_iff_inr R M x).mp hx
    rw [x_inr, ← squareZeroQuotientEquiv_mk_ι x.snd]
    exact Ideal.mem_map_of_mem _
      (Ideal.mk_mem_cotangentIdeal.mpr (ι_mem_augmentationIdeal x.snd))

/-- The quotient equivalence identifies the cotangent ideal with the square-zero kernel,
as modules over the base ring. -/
noncomputable def cotangentIdealEquivKerIdeal :
    (augmentationIdeal (R := R) (M := M)).cotangentIdeal ≃ₗ[R]
      TrivSqZeroExt.kerIdeal R M := by
  let equiv := squareZeroQuotientEquiv (R := R) (M := M)
  apply equiv.toLinearEquiv.ofSubmodules
    ((augmentationIdeal (R := R) (M := M)).cotangentIdeal.restrictScalars R)
    ((TrivSqZeroExt.kerIdeal R M).restrictScalars R)
  apply Submodule.ext
  intro value
  rw [← squareZeroQuotientEquiv_cotangentIdeal (R := R) (M := M)]
  exact (Ideal.mem_map_iff_of_surjective equiv.toRingHom equiv.surjective).symm

/-- The restricted cotangent ideal equivalence acts by the quotient equivalence. -/
@[simp] theorem cotangentIdealEquivKerIdeal_apply
    (x : (augmentationIdeal (R := R) (M := M)).cotangentIdeal) :
    ((cotangentIdealEquivKerIdeal (R := R) (M := M) x :
      TrivSqZeroExt.kerIdeal R M) : TrivSqZeroExt R M) =
      squareZeroQuotientEquiv (R := R) (M := M) x :=
  rfl

/-- The inverse restricted equivalence acts by the inverse quotient equivalence. -/
@[simp] theorem cotangentIdealEquivKerIdeal_symm_apply
    (x : TrivSqZeroExt.kerIdeal R M) :
    ((cotangentIdealEquivKerIdeal (R := R) (M := M)).symm x :
      SymmetricAlgebra R M ⧸ (augmentationIdeal (R := R) (M := M)) ^ 2) =
      (squareZeroQuotientEquiv (R := R) (M := M)).symm x :=
  rfl

/-- The conormal module of the augmentation ideal is the original module, with
its scalar action restricted along `R → SymmetricAlgebra R M`. This equivalence
passes through the cotangent ideal and the projection kernel. -/
noncomputable def augmentationCotangentEquiv :
  (augmentationIdeal (R := R) (M := M)).Cotangent ≃ₗ[R] M :=
  ((augmentationIdeal (R := R) (M := M)).cotangentEquivIdeal).restrictScalars R ≪≫ₗ
    cotangentIdealEquivKerIdeal (R := R) (M := M) ≪≫ₗ
      TrivSqZeroExt.kerIdealLinearEquiv (R := R) (M := M)

/-- The cotangent class of a degree-one element is that element of the module. -/
@[simp] theorem augmentationCotangentEquiv_ι (m : M) :
    augmentationCotangentEquiv (R := R) (M := M)
      ((augmentationIdeal (R := R) (M := M)).toCotangent
        ⟨ι R M m, ι_mem_augmentationIdeal m⟩) = m := by
  change (squareZeroQuotientEquiv (R := R) (M := M)
    (Ideal.Quotient.mk _ (ι R M m))).snd = m
  simp

/-- The inverse cotangent equivalence takes a module element to its degree-one class. -/
@[simp] theorem augmentationCotangentEquiv_symm (m : M) :
    (augmentationCotangentEquiv (R := R) (M := M)).symm m =
      (augmentationIdeal (R := R) (M := M)).toCotangent
        ⟨ι R M m, ι_mem_augmentationIdeal m⟩ := by
  apply (augmentationCotangentEquiv (R := R) (M := M)).injective
  simp

/-- The cotangent comparison respects the canonical scalar restriction. -/
theorem augmentationCotangentEquiv_algebraMap_smul
    (r : R) (x : (augmentationIdeal (R := R) (M := M)).Cotangent) :
    augmentationCotangentEquiv (R := R) (M := M)
      (algebraMap R (SymmetricAlgebra R M) r • x) =
        r • augmentationCotangentEquiv (R := R) (M := M) x := by
  exact (augmentationCotangentEquiv (R := R) (M := M)).map_smul r x

variable {N : Type uN} [AddCommGroup N] [Module R N]

/-- A module map carries augmentation ideals into augmentation ideals. -/
theorem map_augmentationIdeal (f : M →ₗ[R] N) :
    augmentationIdeal (R := R) (M := M) ≤
      (augmentationIdeal (R := R) (M := N)).comap (map f) := by
  have compatibility : (algebraMapInv (R := R) (M := N)).comp (map f) =
      algebraMapInv (R := R) (M := M) := by
    apply SymmetricAlgebra.algHom_ext
    ext m
    simp [algebraMapInv]
  intro x hx
  apply (mem_augmentationIdeal_iff (R := R) (M := N) (map f x)).mpr
  rw [← AlgHom.comp_apply, compatibility]
  exact (mem_augmentationIdeal_iff (R := R) (M := M) x).mp hx

/-- The map on first-order quotients induced by a linear map on generators. -/
noncomputable def squareZeroQuotientMap (f : M →ₗ[R] N) :
    (SymmetricAlgebra R M ⧸ (augmentationIdeal (R := R) (M := M)) ^ 2) →ₐ[R]
      (SymmetricAlgebra R N ⧸ (augmentationIdeal (R := R) (M := N)) ^ 2) :=
  Ideal.quotientMapₐ _ (map f) (by
    intro x hx
    have mapped : map f x ∈ Ideal.map (map f).toRingHom
        ((augmentationIdeal (R := R) (M := M)) ^ 2) :=
      Ideal.mem_map_of_mem _ hx
    rw [Ideal.map_pow] at mapped
    exact pow_le_pow_left'
      (Ideal.map_le_iff_le_comap.mpr (map_augmentationIdeal f)) 2 mapped)

/-- The induced map applies the symmetric-algebra map before taking a quotient class. -/
@[simp] theorem squareZeroQuotientMap_mk (f : M →ₗ[R] N)
    (x : SymmetricAlgebra R M) :
    squareZeroQuotientMap f (Ideal.Quotient.mk _ x) =
      Ideal.Quotient.mk _ (map f x) := by
  simp [squareZeroQuotientMap]

/-- The first-order quotient equivalence is natural as an equality of algebra maps. -/
theorem squareZeroQuotientEquiv_naturality (f : M →ₗ[R] N) :
    (squareZeroQuotientEquiv (R := R) (M := N)).toAlgHom.comp
      (squareZeroQuotientMap f) =
        (TrivSqZeroExt.map f).comp
          (squareZeroQuotientEquiv (R := R) (M := M)).toAlgHom := by
  apply Ideal.Quotient.algHom_ext
  apply SymmetricAlgebra.algHom_ext
  apply LinearMap.ext
  intro m
  change squareZeroQuotientEquiv (R := R) (M := N)
    (squareZeroQuotientMap f (Ideal.Quotient.mk _ (ι R M m))) =
      TrivSqZeroExt.map f
        (squareZeroQuotientEquiv (R := R) (M := M)
          (Ideal.Quotient.mk _ (ι R M m)))
  simp

/-- The conormal equivalence is natural for the induced cotangent map. -/
theorem augmentationCotangentEquiv_naturality (f : M →ₗ[R] N) :
    (augmentationCotangentEquiv (R := R) (M := N)).toLinearMap.comp
      (Ideal.mapCotangent
        (augmentationIdeal (R := R) (M := M))
        (augmentationIdeal (R := R) (M := N)) (map f) (map_augmentationIdeal f)) =
      f.comp (augmentationCotangentEquiv (R := R) (M := M)).toLinearMap := by
  apply LinearMap.ext
  intro x
  obtain ⟨m, rfl⟩ :=
    (augmentationCotangentEquiv (R := R) (M := M)).symm.surjective x
  simp only [LinearMap.comp_apply, augmentationCotangentEquiv_symm,
    Ideal.mapCotangent_toCotangent, map_ι_apply]
  change augmentationCotangentEquiv (R := R) (M := N)
      ((augmentationIdeal (R := R) (M := N)).toCotangent
        ⟨ι R N (f m), _⟩) =
    f (augmentationCotangentEquiv (R := R) (M := M)
      ((augmentationIdeal (R := R) (M := M)).toCotangent
        ⟨ι R M m, ι_mem_augmentationIdeal m⟩))
  simp

end SymmetricAlgebra

end
