/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier contributor (Hive Task hive-request-45b307ef0b08baacd6a851dadec8faa23ee22d69,
  UID 65fe43bb-2c1b-4320-b724-f8b1f1fa063a)
-/
module

public import GradedRings.Veronese
public import GradedRings.HomogeneousLifts

/-!
# Degree-one generation of positive selected-component graded rings

Selecting every component of degree divisible by a positive integer preserves generation
by the complete degree-one component over the actual degree-zero ring.
-/

@[expose] public section

set_option warningAsError true

noncomputable section

namespace GradedRing.Veronese

universe u v

variable {S : Type u} [CommRing S] {σ : Type v} [SetLike σ S]
  [AddSubgroupClass σ S] (𝒮 : ℕ → σ) [GradedRing 𝒮]

private theorem homogeneousSubmodule_mul_eq_pow (n j : ℕ) :
    MvPolynomial.homogeneousSubmodule (𝒮 1) (𝒮 0) (n * j) =
      (MvPolynomial.homogeneousSubmodule (𝒮 1) (𝒮 0) n) ^ j := by
  calc
    _ = (MvPolynomial.homogeneousSubmodule (𝒮 1) (𝒮 0) 1) ^ (n * j) :=
      (MvPolynomial.homogeneousSubmodule_one_pow (𝒮 0) (n * j)).symm
    _ = ((MvPolynomial.homogeneousSubmodule (𝒮 1) (𝒮 0) 1) ^ n) ^ j :=
      (pow_mul _ n j)
    _ = _ := by rw [MvPolynomial.homogeneousSubmodule_one_pow]

private theorem eval_mem_adjoin (n : ℕ) (hn : 0 < n) (j : ℕ)
    {p : MvPolynomial (𝒮 1) (𝒮 0)}
    (hp : p ∈ (MvPolynomial.homogeneousSubmodule (𝒮 1) (𝒮 0) n) ^ j) :
    ∃ t : VeroneseRing 𝒮 n,
      t ∈ Algebra.adjoin (component 𝒮 n 0) (component 𝒮 n 1 : Set (VeroneseRing 𝒮 n)) ∧
        inclusion 𝒮 n t = MvPolynomial.aeval (fun a : 𝒮 1 => (a : S)) p := by
  let U : Subalgebra (component 𝒮 n 0) (VeroneseRing 𝒮 n) :=
    Algebra.adjoin (component 𝒮 n 0) (component 𝒮 n 1 : Set (VeroneseRing 𝒮 n))
  let e : MvPolynomial (𝒮 1) (𝒮 0) →ₐ[𝒮 0] S :=
    MvPolynomial.aeval (fun a : 𝒮 1 => (a : S))
  change ∃ t : VeroneseRing 𝒮 n, t ∈ U ∧ inclusion 𝒮 n t = e p
  apply Submodule.pow_induction_on_left
    (M := MvPolynomial.homogeneousSubmodule (𝒮 1) (𝒮 0) n)
    (C := fun p => ∃ t : VeroneseRing 𝒮 n, t ∈ U ∧ inclusion 𝒮 n t = e p)
    (hx := hp)
  · intro r
    let t : VeroneseRing 𝒮 n :=
      algebraMap (component 𝒮 n 0) (VeroneseRing 𝒮 n) ((zeroRingEquiv 𝒮 n hn).symm r)
    refine ⟨t, U.algebraMap_mem _, ?_⟩
    dsimp [t]
    change inclusion 𝒮 n (((zeroRingEquiv 𝒮 n hn).symm r : component 𝒮 n 0) :
      VeroneseRing 𝒮 n) = e (algebraMap _ _ r)
    rw [← zeroRingEquiv_apply 𝒮 n hn]
    simp only [RingEquiv.apply_symm_apply]
    simp only [e, AlgHom.commutes, SetLike.GradeZero.algebraMap_apply]
  · intro p q hp hq
    obtain ⟨t, ht, heq⟩ := hp
    obtain ⟨s, hs, hsq⟩ := hq
    refine ⟨t + s, U.add_mem ht hs, ?_⟩
    rw [map_add, heq, map_add, hsq]
  · intro a ha p hp
    obtain ⟨t, ht, heq⟩ := hp
    have ha' : e a ∈ 𝒮 (n * 1) := by
      simpa only [mul_one] using
        MvPolynomial.isHomogeneous_aeval_degreeOne 𝒮
          ((MvPolynomial.mem_homogeneousSubmodule n a).mp ha)
    obtain ⟨b, hb, hbeq⟩ := exists_component 𝒮 n 1 ⟨e a, ha'⟩
    refine ⟨b * t, U.mul_mem (Algebra.subset_adjoin hb) ht, ?_⟩
    rw [map_mul, hbeq, heq, map_mul]

/-- A positive Veronese ring of a degree-one-generated graded ring is generated by
its complete new degree-one component over its actual new degree-zero ring. -/
theorem adjoin_component_one_eq_top (n : ℕ) (hn : 0 < n)
    (hgen : Algebra.adjoin (𝒮 0) (𝒮 1 : Set S) = ⊤) :
    Algebra.adjoin (component 𝒮 n 0)
      (component 𝒮 n 1 : Set (VeroneseRing 𝒮 n)) = ⊤ := by
  let U : Subalgebra (component 𝒮 n 0) (VeroneseRing 𝒮 n) :=
    Algebra.adjoin (component 𝒮 n 0) (component 𝒮 n 1 : Set (VeroneseRing 𝒮 n))
  apply top_unique
  intro x _
  have h : ∀ x : VeroneseRing 𝒮 n, x ∈ U := by
   intro x
   induction x using DirectSum.induction_on with
  | zero => exact U.zero_mem
  | of j s =>
    obtain ⟨p, hhom, hp⟩ := MvPolynomial.exists_isHomogeneous_aeval 𝒮 hgen s.property
    have hmem : p ∈ (MvPolynomial.homogeneousSubmodule (𝒮 1) (𝒮 0) n) ^ j := by
      rw [← homogeneousSubmodule_mul_eq_pow 𝒮 n j]
      exact (MvPolynomial.mem_homogeneousSubmodule (n * j) p).mpr hhom
    obtain ⟨t, ht, heq⟩ := eval_mem_adjoin 𝒮 n hn j hmem
    have ht' : t = DirectSum.of (fun k : ℕ => 𝒮 (n * k)) j s :=
      inclusion_injective 𝒮 n hn (heq.trans (hp.trans (inclusion_of 𝒮 n j s).symm))
    exact ht' ▸ ht
   | add x y hx hy => exact U.add_mem hx hy
  exact h x

end GradedRing.Veronese
