/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import GradedRings.WeightedBlocks
public import Mathlib.RingTheory.MvPolynomial.WeightedHomogeneous
public import Mathlib.RingTheory.Adjoin.Basic

@[expose] public section

/-!
# Weighted-homogeneous polynomials in a monomial adjoin

For positive natural weights on a finite index type, a polynomial homogeneous at
a multiple of `Finsupp.weightedBlockSize` lies in the coefficient subalgebra
generated by the monomials of that block weight.
-/

namespace MvPolynomial

variable {ι R : Type*} [Fintype ι] [CommSemiring R]

private theorem monomial_mem_adjoin_weightedBlockSize
    (w : ι → ℕ) (hw : ∀ i, 0 < w i) (k : ℕ)
    (d : ι →₀ ℕ) (r : R)
    (hd : Finsupp.weight w d = k * Finsupp.weightedBlockSize w) :
    monomial d r ∈ Algebra.adjoin R
      ((fun e : ι →₀ ℕ => monomial e (1 : R)) ''
        {e | Finsupp.weight w e = Finsupp.weightedBlockSize w}) := by
  classical
  obtain ⟨blocks, hsum, hweight⟩ := Finsupp.exists_weightedBlocks w hw k d hd
  rw [← hsum, monomial_sum_index]
  apply Subalgebra.mul_mem
  · simpa only [algebraMap_eq] using
      (Algebra.adjoin R
        ((fun e : ι →₀ ℕ => monomial e (1 : R)) ''
          {e | Finsupp.weight w e = Finsupp.weightedBlockSize w})).algebraMap_mem r
  · apply Subalgebra.prod_mem
    intro j _
    exact Algebra.subset_adjoin ⟨blocks j, hweight j, rfl⟩

/-- A weighted-homogeneous polynomial of degree divisible by the positive-weight
block size belongs to the coefficient subalgebra generated by weight-one-block
monomials. Coefficients are unrestricted, including when `k = 0`. -/
theorem IsWeightedHomogeneous.mem_adjoin_weightedBlockSize
    (w : ι → ℕ) (hw : ∀ i, 0 < w i) (k : ℕ) {p : MvPolynomial ι R}
    (hp : p.IsWeightedHomogeneous w (k * Finsupp.weightedBlockSize w)) :
    p ∈ Algebra.adjoin R
      ((fun d : ι →₀ ℕ => monomial d (1 : R)) ''
        {d | Finsupp.weight w d = Finsupp.weightedBlockSize w}) := by
  induction hp using IsWeightedHomogeneous.induction_on with
  | zero => exact Subalgebra.zero_mem _
  | add p q hp hq ihp ihq => exact Subalgebra.add_mem _ ihp ihq
  | monomial d r hd => exact monomial_mem_adjoin_weightedBlockSize w hw k d r hd

end MvPolynomial
