/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import Mathlib.RingTheory.MvPolynomial.WeightedHomogeneous
public import Mathlib.RingTheory.Adjoin.Basic

/-!
# Finite generators for selected weighted polynomial degrees

For any positive index and arbitrary natural weights, the polynomials whose weighted degrees
are multiples of that index lie in the coefficient algebra generated by a finite family of
homogeneous monomials. Zero weights and the empty variable type are allowed.
-/

set_option warningAsError true

@[expose] public section

open Finset

namespace MvPolynomial

universe u v

variable {ι : Type u} {R : Type v} [CommSemiring R]

section

variable [Fintype ι]

private noncomputable def weightedResidues (w : ι → ℕ) (n : ℕ) : Finset (ι →₀ ℕ) := by
  classical
  exact ((Finset.univ : Finset (ι → Fin n)).image fun f =>
    Finsupp.equivFunOnFinite.symm (fun i => (f i).val)).filter
      (fun b => n ∣ Finsupp.weight w b)

private noncomputable def residue (n : ℕ) (a : ι →₀ ℕ) : ι →₀ ℕ :=
  Finsupp.equivFunOnFinite.symm (fun i => a i % n)

private noncomputable def weightedGenerators (w : ι → ℕ) (n : ℕ) :
    Finset (MvPolynomial ι R) := by
  classical
  exact (Finset.univ.image (fun i : ι => (X i : MvPolynomial ι R) ^ n)) ∪
    (weightedResidues w n).image (fun b => monomial b (1 : R))

private theorem residue_apply (n : ℕ) (a : ι →₀ ℕ) (i : ι) :
    residue n a i = a i % n := rfl

private theorem residue_mem (w : ι → ℕ) (n : ℕ) (hn : 0 < n) (a : ι →₀ ℕ)
    (ha : n ∣ Finsupp.weight w a) : residue n a ∈ weightedResidues w n := by
  classical
  have hweight : Finsupp.weight w a =
      n * (∑ i, (a i / n) * w i) + Finsupp.weight w (residue n a) := by
    calc
      Finsupp.weight w a = ∑ i, a i * w i := by simp [Finsupp.weight_eq_sum]
      _ = ∑ i, (n * (a i / n) + residue n a i) * w i := by
        apply Finset.sum_congr rfl
        intro i _
        congr 1
        rw [residue_apply]
        have h := Nat.mod_add_div (a i) n
        omega
      _ = n * (∑ i, (a i / n) * w i) + Finsupp.weight w (residue n a) := by
        simp [Finsupp.weight_eq_sum, Finset.sum_add_distrib,
          Finset.mul_sum, Nat.add_mul, mul_assoc]
  have hdiv : n ∣ Finsupp.weight w (residue n a) := by
    rw [hweight] at ha
    exact (Nat.dvd_add_iff_right (dvd_mul_right n _)).mpr ha
  change residue n a ∈ ((Finset.univ : Finset (ι → Fin n)).image fun f =>
    Finsupp.equivFunOnFinite.symm (fun i => (f i).val)).filter (fun b =>
    n ∣ Finsupp.weight w b)
  apply Finset.mem_filter.mpr
  constructor
  · apply Finset.mem_image.mpr
    refine ⟨fun i => ⟨a i % n, Nat.mod_lt _ hn⟩, Finset.mem_univ _, ?_⟩
    apply Finsupp.ext
    intro i
    simp [residue]
  · exact hdiv

private theorem monomial_one_eq_prod (a : ι →₀ ℕ) :
    (monomial a (1 : R)) = ∏ i : ι, (X i : MvPolynomial ι R) ^ a i := by
  classical
  rw [monomial_eq, map_one, one_mul]
  exact Finsupp.prod_fintype _ _ (by simp)

private theorem monomial_mem_adjoin (w : ι → ℕ) (n : ℕ) (hn : 0 < n)
    (a : ι →₀ ℕ) (ha : n ∣ Finsupp.weight w a) :
    monomial a (1 : R) ∈ Algebra.adjoin R
      (weightedGenerators (R := R) w n : Set (MvPolynomial ι R)) := by
  classical
  let r := residue n a
  have hr : monomial r (1 : R) ∈ Algebra.adjoin R
      (weightedGenerators (R := R) w n : Set (MvPolynomial ι R)) := by
    apply Algebra.subset_adjoin
    change monomial r (1 : R) ∈
      (Finset.univ.image (fun i : ι => (X i : MvPolynomial ι R) ^ n)) ∪
        (weightedResidues w n).image (fun b => monomial b (1 : R))
    exact Finset.mem_union_right _
      (Finset.mem_image.mpr ⟨r, residue_mem w n hn a ha, rfl⟩)
  have hpure (i : ι) : (X i : MvPolynomial ι R) ^ n ∈ Algebra.adjoin R
      (weightedGenerators (R := R) w n : Set (MvPolynomial ι R)) := by
    apply Algebra.subset_adjoin
    change (X i : MvPolynomial ι R) ^ n ∈
      (Finset.univ.image (fun i : ι => (X i : MvPolynomial ι R) ^ n)) ∪
        (weightedResidues w n).image (fun b => monomial b (1 : R))
    exact Finset.mem_union_left _
      (Finset.mem_image.mpr ⟨i, Finset.mem_univ _, rfl⟩)
  have hfactor : monomial a (1 : R) =
      (∏ i : ι, ((X i : MvPolynomial ι R) ^ n) ^ (a i / n)) * monomial r 1 := by
    rw [monomial_one_eq_prod, monomial_one_eq_prod]
    rw [← Finset.prod_mul_distrib]
    apply Finset.prod_congr rfl
    intro i _
    rw [← pow_mul, ← pow_add]
    congr 1
    simp only [r, residue_apply]
    have h := Nat.mod_add_div (a i) n
    omega
  rw [hfactor]
  exact mul_mem (prod_mem (fun i _ => pow_mem (hpure i) _)) hr

end

attribute [local instance] Fintype.ofFinite in
/-- A finite family of homogeneous polynomials generates every weighted component whose
degree is divisible by a prescribed positive index, over the entire coefficient semiring. -/
theorem exists_finset_weightedVeronese_generators [Finite ι]
    (w : ι → ℕ) (n : ℕ) (hn : 0 < n) :
    ∃ T : Finset (MvPolynomial ι R),
      (∀ p ∈ T, ∃ j : ℕ, p.IsWeightedHomogeneous w (n * j)) ∧
      ∀ j : ℕ, ∀ p : MvPolynomial ι R,
        p.IsWeightedHomogeneous w (n * j) →
          p ∈ Algebra.adjoin R (T : Set (MvPolynomial ι R)) := by
  classical
  let T : Finset (MvPolynomial ι R) := weightedGenerators (R := R) w n
  refine ⟨T, ?_, ?_⟩
  · intro p hp
    change p ∈ (Finset.univ.image (fun i : ι => (X i : MvPolynomial ι R) ^ n)) ∪
      (weightedResidues w n).image (fun b => monomial b (1 : R)) at hp
    rcases Finset.mem_union.mp hp with hp | hp
    · obtain ⟨i, _, rfl⟩ := Finset.mem_image.mp hp
      exact ⟨w i, by simpa [mul_comm] using
        (isWeightedHomogeneous_X (R := R) w i).pow n⟩
    · obtain ⟨b, hb, rfl⟩ := Finset.mem_image.mp hp
      obtain ⟨j, hj⟩ := (Finset.mem_filter.mp hb).2
      exact ⟨j, isWeightedHomogeneous_monomial w b 1 (by simpa [mul_comm] using hj)⟩
  · intro j p hp
    apply hp.induction_on
    · exact zero_mem _
    · intro p q hp hq ihp ihq
      exact add_mem ihp ihq
    · intro a c ha
      have hunit := monomial_mem_adjoin (R := R) w n hn a
        ⟨j, by simpa [mul_comm] using ha⟩
      have hcoeff := (Algebra.adjoin R (T : Set (MvPolynomial ι R))).algebraMap_mem c
      simpa only [algebraMap_eq, C_mul_monomial, mul_one] using
        (mul_mem hcoeff hunit)

end MvPolynomial
